drop table if exists statistics;

create table if not exists statistics
(
id        bigint generated by default as identity not null,
app       varchar(255) not null,
uri       varchar(255) not null,
ip        varchar(255) not null,
created   timestamp without time zone not null,
constraint pk_statistics primary key (id)
);