version: '3.1'
services:

  stats-server:
    build: stats-module/stats-service
    image: stats-service-image
    container_name: stats-service-cont
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - DB_NAME=ewm-stats
      - DB_USER=ewm-stats
      - DB_PASSWORD=ewm-stats
      - DB_HOST=stats-db
      - DB_PORT=5432

  stats-db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=ewm-stats
      - POSTGRES_USER=ewm-stats
      - POSTGRES_PASSWORD=ewm-stats
    volumes:
      - /var/lib/postgresql/data/

  ewm-service:
    build: ./main-module
    image: ewm-service-image
    container_name: ewm-service-cont
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - DB_NAME=ewm-main
      - DB_USER=ewm-main
      - DB_PASSWORD=ewm-main
      - DB_HOST=ewm-db
      - DB_PORT=5432

  ewm-db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=ewm-main
      - POSTGRES_USER=ewm-main
      - POSTGRES_PASSWORD=ewm-main
    volumes:
      - /var/lib/postgresql/data/
