drop table if exists compilations_events, requests, events, locations, categories, users, compilations cascade;

create table if not exists users (
    id    bigint       generated by default as identity primary key,
    name  varchar(100) not null,
    email varchar(100) not null unique
    );

create table if not exists categories (
    id    bigint generated by default as identity primary key,
    name  varchar(100) not null unique
    );

create table if not exists locations (
    id    bigint generated by default as identity primary key,
    lat   double precision not null,
    lon   double precision not null
    );

create table if not exists events (
    id                      bigint generated by default as identity primary key,
    annotation              varchar(2000)                   not null,
    category_id             bigint                          not null references categories(id),
    created_on              timestamp without time zone     not null,
    description             varchar(7000)                   not null,
    event_date              timestamp without time zone     not null,
    initiator_id            bigint                          not null references users(id) on delete cascade,
    location_id             bigint                          not null references locations(id) on delete cascade,
    is_paid                 boolean                         not null,
    participant_limit       int                             not null,
    published_on            timestamp without time zone,
    is_request_moderation   boolean                         not null,
    state                   varchar(20)                     not null,
    title                   varchar(120)                    not null unique
    );

create table if not exists requests (
    id             bigint generated by default as identity primary key,
    created        timestamp without time zone   not null,
    event_id       bigint                        not null references events(id) on delete cascade,
    requester_id   bigint                        not null references users(id) on delete cascade,
    status         varchar(20)                   not null,
    constraint requester_unique unique (event_id, requester_id)
    );

create table if not exists compilations (
    id      bigint       generated by default as identity primary key,
    pinned  boolean      not null,
    title   varchar(50)  not null
    );

create table if not exists compilations_events (
    compilations_id   bigint   not null references compilations (id) on delete cascade,
    events_id         bigint   not null references events (id) on delete cascade,
    constraint compilations_events_unique unique (compilations_id, events_id)
    );